### ISSUE TITLE
Folder not empty error

### ISSUE THREAD

**Issue by camjac251** [mrworf/plexupdate#44] opened 2016-03-01 08:09 UTC
When running the update, I would get cannot delete directory; not empty, when it tries to presumably replace the bundles with updated info. Is this normal?

**Comment by judhat2** [comment] 2016-03-01 13:25
I get that also, but I don't know the reason or how to fix it.

**Comment by mrworf** [comment] 2016-03-01 15:44
Does it still install the update? Can you provide a complete log output here for analysis?

**Comment by judhat2** [comment] 2016-03-01 16:17
Yes, it still updates and functions correctly as far as I know.  I don't know where the log is found, but next time there is an update, I'll save the output.

**Comment by judhat2** [comment] 2016-03-01 16:31
For me, it looks like this. I don't think it is the script's fault.

```
user@Ethernet:~/plexupdate# bash plexupdate.sh -p -a -d
Finding download URL for 64-bit...OK
Downloading release "plexmediaserver_0.9.15.6.1714-7be11e1_amd64.deb"...OK
(Reading database ... 40447 files and directories currently installed.)
Preparing to unpack .../plexmediaserver_0.9.15.6.1714-7be11e1_amd64.deb ...
plexmediaserver stop/waiting
Unpacking plexmediaserver (0.9.15.6.1714-7be11e1) over (0.9.15.2.1663-7efd046) ...
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/Framework.bundle/Contents/Resources/Versions/2/Python/subsystem': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/handlers': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/modelling': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/policies': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/components': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/code': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/interfaces': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/Framework.bundle/Contents/Resources/Versions/2/Python/Framework': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/Framework.bundle/Contents/Resources/Versions/2/Python': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/Framework.bundle/Contents/Resources/Versions/2': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/Framework.bundle/Contents/Resources/Versions': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/tornado': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/routes': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/crypto/keyedHash': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/crypto/cipher': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/crypto/hash': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/crypto': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/RestrictedPython': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/pyamf/adapters': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/pyamf/util': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/pyamf/remoting/client': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/pyamf/remoting': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/pyamf': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/dateutil': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries/cerealizer': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/Framework.bundle/Contents/Resources/Platforms/Shared/Libraries': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/Framework.bundle/Contents/Resources/Platforms/Shared': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/Framework.bundle/Contents/Resources/Platforms': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/Framework.bundle/Contents/Resources': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/Framework.bundle/Contents': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/Framework.bundle': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/LocalMedia.bundle/Contents/Libraries/Shared/mutagen': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/LocalMedia.bundle/Contents/Libraries/Shared': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/LocalMedia.bundle/Contents/Libraries': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/LocalMedia.bundle/Contents': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046/LocalMedia.bundle': Directory not empty
dpkg: warning: unable to delete old directory '/usr/lib/plexmediaserver/Resources/Plug-ins-7efd046': Directory not empty
Setting up plexmediaserver (0.9.15.6.1714-7be11e1) ...
plexmediaserver start/running, process 32303
Processing triggers for mime-support (3.54ubuntu1.1) ...
Deleted "plexmediaserver_0.9.15.6.1714-7be11e1_amd64.deb"
```

**Comment by mrworf** [comment] 2016-03-01 16:33
You're right, that's coming from dpkg's upgrade process. You probably have a modified file and/or added plugin to Plex which is now affecting the upgrade process.

**Comment by mrworf** [comment] 2016-03-15 03:52
Closing this since it's clearly caused by extra files installed by the end-user and not dealt with by the ubuntu package.

**Closed by mrworf** 2016-03-15 03:52 UTC
