### ISSUE TITLE
Error Since Latest Plex Version

### ISSUE THREAD

**Issue by rjsears** [mrworf/plexupdate#15] opened 2015-08-10 20:16 UTC
root@cinaplex:~# /root/plexupdate.sh
Authenticating...OK
Finding download URL for 64-bit...OK
Sorry, page layout must have changed, I'm unable to retrieve the URL needed for download
root@cinaplex:~#

**Comment by bcin** [comment] 2015-08-10 20:31
Getting a "500" error on the PlexPass download page. Suspect this is the cause.

https://plex.tv/downloads?channel=plexpass

**Comment by rjsears** [comment] 2015-08-10 20:38
Wow..I must have just caught it at the right time...the script didn't work, I waited about 5 minutes doing something else and downloaded it manually and updated Plex. Must have hit the 500 with the script and when I did it manually it was back online!

Thanks!!

**Comment by bcin** [comment] 2015-08-10 22:00
from reddit/r/plex today:

Notice from the forums: Notice: The database upgrade has been PUSHED UP and
is now 2015-08-10 from 2:30-3:30pm PDT (21:30-22:30 GMT). This will affect
access to the website and login services, among other things.

It's completely down for me. Fingers crossed it will return later, intact
and allow Mr. Worf's script to continue to work.

**Comment by mrworf** [comment] 2015-08-14 00:49
Seems to be working fine now. Closing issue

**Closed by mrworf** 2015-08-14 00:49 UTC
