### ISSUE TITLE
ERROR: Server 127.0.0.1 is currently being used by one or more users, skipping installation. Please run again later

### ISSUE THREAD

**Issue by derekcentrico** [mrworf/plexupdate#227] opened 2018-03-10 01:43 UTC
Using the series of commits in #226 via version-checks branch.  Downloaded the ZIP of that and replaced the master branch which wouldn't update for me. 

> Retrieving list of available distributions
> Downloading release "plexmediaserver_1.12.0.4829-6de959918_amd64.deb"
> File downloaded
> ERROR: Server 127.0.0.1 is currently being used by one or more users, skipping installation. Please run again later
> 

No one is streaming right now.  The only thing I can dream of as "being used" would be some application or system is still connected such as Android TV apps on a Shield or Nexus Player, etc.  

![screenshot 2018-03-09 at 8 42 32 pm](https://user-images.githubusercontent.com/1930094/37236884-92824806-23da-11e8-9c58-2e4deaa6ad24.png)

Thoughts?

**Comment by demonbane** [comment] 2018-03-10 01:57
First, I'd like to get you back on master just to confirm that that's where the issue is (I just merged activity checking code into master last night that is also reflected in the version-checks branch).

If you just go into your plexupdate directory and type `git checkout master` it **should** cleanly switch you back to master. If that doesn't work, or if you're already on master, you can do `git reset --hard origin/master` instead.

As for the actual issue, I'll need a bit more data. You'll need to fetch your token and then manually check the status pages for your Plex server. You should just be able to paste the below into a terminal (in your plexupdate directory).

```sh
TOKEN=$(bash -c 'source plexupdate-core' get-plex-token | cut -f3 -d" ")
wget --no-check-certificate -q -O - "https://127.0.0.1:32400/status/sessions?X-Plex-Token=$TOKEN"
wget --no-check-certificate -q -O - "https://127.0.0.1:32400/livetv/sessions?X-Plex-Token=$TOKEN"
```

If your Plex server is using a different IP/port number be sure to update that in the wget lines above. If you happen to get an SSL error (you shouldn't), remove `--no-check-certificate` and change `https` to `http`.

**Comment by demonbane** [comment] 2018-03-10 02:02
Oh, and if you can also run `awk --version`. Just in case.

**Comment by derekcentrico** [comment] 2018-03-10 02:04
Okay, back on master.  Same issue

> Configuration complete. Would you like to run plexupdate with these settings now? [Y/n] Y
Retrieving list of available distributions
File already exists (plexmediaserver_1.12.0.4829-6de959918_amd64.deb), won't download.
ERROR: Server 127.0.0.1 is currently being used by one or more users, skipping installation. Please run again later

> wget --no-check-certificate -q -O - "https://127.0.0.1:32400/status/sessions?X-Plex-Token=$TOKEN"
<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="0">
</MediaContainer>
root@homeserver:/etc/plexupdate# wget --no-check-certificate -q -O - "https://127.0.0.1:32400/livetv/sessions?X-Plex-Token=$TOKEN"
<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="0">
</MediaContainer>

GNU Awk 4.1.3, API: 1.1 (GNU MPFR 3.1.4, GNU MP 6.1.0)

**Comment by demonbane** [comment] 2018-03-10 02:06
wget should have produced a good chunk of output in XML, that's what I need to see.

**Comment by derekcentrico** [comment] 2018-03-10 02:09
of note, "Writing configuration file '/etc/plexupdate.conf'... done"

This file does not exist in the DIR.

drwxr-xr-x   4 root root 4.0K Mar  9 21:07 .
drwxr-xr-x 199 root root  12K Mar  9 21:01 ..
drwxrwxr-x   2 root root 4.0K Mar  9 21:01 extras
drwxrwxr-x   8 root root 4.0K Mar  9 21:02 .git
-rw-rw-r--   1 root root  18K Mar  9 21:01 LICENSE
-rwxrwxr-x   1 root root 6.8K Mar  9 21:01 plexupdate-core
-rwxrwxr-x   1 root root  17K Mar  9 21:07 plexupdate.sh
-rwxrwxr-x   1 root root 5.2K Mar  9 21:01 README.md
derek@homeserver:/etc/plexupdate$

**Comment by demonbane** [comment] 2018-03-10 02:11
@derekcentrico Yup, it's showing you the full path. It's not in your plexupdate directory, it's a file called `plexupdate.conf` in the `/etc` directory.

**Comment by derekcentrico** [comment] 2018-03-10 02:14
Doh.  I didn't read and had hoped that was the issue.  So, the output of wget is still the same small media headers.  I tried the setup and the wget commands with the LAN IP and the 127.  Nothing is functional for me.

**Comment by derekcentrico** [comment] 2018-03-10 02:28
Hmm, funny thing is this puppy works IF plex is not running.

root@homeserver:/etc/plexupdate# bash plexupdate.sh
Retrieving list of available distributions
File already exists (plexmediaserver_1.12.0.4829-6de959918_amd64.deb), won't download.
ERROR: Server 192.168.1.49 is currently being used by one or more users, skipping installation. Please run again later
root@homeserver:/etc/plexupdate# service plexmediaserver stop
root@homeserver:/etc/plexupdate# bash plexupdate.sh
Retrieving list of available distributions
File already exists (plexmediaserver_1.12.0.4829-6de959918_amd64.deb), won't download.
(Reading database ... 637576 files and directories currently installed.)
Preparing to unpack .../plexmediaserver_1.12.0.4829-6de959918_amd64.deb ...
Removed symlink /etc/systemd/system/multi-user.target.wants/plexmediaserver.service.
Unpacking plexmediaserver (1.12.0.4829-6de959918) over (1.11.3.4803-c40bba82e) ...
Setting up plexmediaserver (1.12.0.4829-6de959918) ...
Created symlink from /etc/systemd/system/multi-user.target.wants/plexmediaserver.service to /etc/systemd/system/plexmediaserver.service.
Processing triggers for systemd (229-4ubuntu21.1) ...
Processing triggers for ureadahead (0.100.0-19) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20180209-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for desktop-file-utils (0.22-1ubuntu5.1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...

**Comment by demonbane** [comment] 2018-03-10 02:33
Oh, looks like GitHub filtered out the XML since it wasn't in a code block. (you can put pastes inside a [fenced code block](https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks) by putting \`\`\` before and after the pasted content)

Hmm. So, it definitely **shouldn't** be saying the server is busy. The code that does that check intentionally says the server **isn't** busy unless it's absolutely certain that it is. Now that the update has worked, can you try redoing it (by running `plexupdate.sh -f`) after Plex is back up and running?

**Comment by derekcentrico** [comment] 2018-03-10 02:35
Yeah, just did it and same thing.

root@homeserver:/etc/plexupdate# bash plexupdate.sh -f
Retrieving list of available distributions
File already exists (plexmediaserver_1.12.0.4829-6de959918_amd64.deb), won't download.
ERROR: Server 192.168.1.49 is currently being used by one or more users, skipping installation. Please run again later

**Comment by demonbane** [comment] 2018-03-10 02:36
Just to confirm, 192.168.1.49 is the local machine that you're running plexupdate on, correct? Have you tried doing the `wget` commands above using that IP?

**Comment by derekcentrico** [comment] 2018-03-10 02:37
Yes, it's the same machine.  I tried both 192.168.1.49 and 127.0.0.1.  Both return the same wget command code.

**Comment by demonbane** [comment] 2018-03-10 02:38
Ok, one second. I'm going to create a new branch with a ton of extra logging to help us get to the bottom of this.

**Comment by derekcentrico** [comment] 2018-03-10 02:40
Bad to post here for development stuff....but I'm here until the wife tells me I have to take my turn getting the baby to try and sleep lol.  So let's roll...until then.

**Comment by demonbane** [comment] 2018-03-10 02:50
Ok, here's the updated branch that should give us every bit of output. Just run
```
git fetch && git checkout verbose-for-227
```
from inside your plexupdate directory and then try running plexupdate again.

**Comment by derekcentrico** [comment] 2018-03-10 03:08
Allrighty...

root@homeserver:/etc/plexupdate# bash plexupdate.sh -f
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
Retrieving list of available distributions
File already exists (plexmediaserver_1.12.0.4829-6de959918_amd64.deb), won't download.
Entered runningFirst wget returned 6, with data:


Second wget returned 6, data is now:


Entering https blockTOKEN is non-zero, continuingFirst https wget returned 0, with data:
<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="0">
</MediaContainer>

Second https wget returned 0, data is now:
<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="0">
</MediaContainer><?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="0">
</MediaContainer>

mediacount is now "1"ERROR: Server 192.168.1.49 is currently being used by one or more users, skipping installation. Please run again later

**Comment by demonbane** [comment] 2018-03-10 03:23
(and don't forget to enclose your output in \`\`\` when you paste it here so it's easier to read)

**Comment by derekcentrico** [comment] 2018-03-10 03:56
Okay, so after running plexupdater.sh it returns to terminal prompt.

I pasted the awk into the prompt and pressed enter.  In the blank line I pasted the below.  Finally, I used Ctrl+D.

```
root@homeserver:/etc/plexupdate# awk -F'"' '/<MediaContainer size="[0-9]+">/ {count+=$2}; /<Player[^>]* state="paused"/ {count--}; END {print count, "\n"}'
<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="0">
</MediaContainer><?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="0">
</MediaContainer>
0 
```

**Comment by demonbane** [comment] 2018-03-10 03:57
And plexupdate.sh is still giving you the in-use error?

**Comment by derekcentrico** [comment] 2018-03-10 03:58
correct.

**Comment by demonbane** [comment] 2018-03-10 04:04
Can you run `plexupdate.sh -f` one more time and paste the output?

**Comment by derekcentrico** [comment] 2018-03-10 04:12
Sure, so firstly I decided to NETSTAT this puppy.

```
tcp        0      0 192.168.1.49:56572      54.171.211.233:80       CLOSE_WAIT  13066/Plex Tuner Se
tcp        1      0 127.0.0.1:55460         127.0.0.1:45851         CLOSE_WAIT  13066/Plex Tuner Se
tcp        1      0 127.0.0.1:55462         127.0.0.1:45851         CLOSE_WAIT  13066/Plex Tuner Se
tcp       32      0 192.168.1.49:37596      54.154.41.222:443       CLOSE_WAIT  13066/Plex Tuner Se
tcp        0      0 192.168.1.49:38662      45.79.198.112:443       ESTABLISHED 12992/Plex Media Se
tcp6       0      0 192.168.1.49:32400      192.168.1.196:46002     ESTABLISHED 12992/Plex Media Se
tcp6       0      0 192.168.1.49:32400      192.168.1.164:37702     ESTABLISHED 12992/Plex Media Se
tcp6       0      0 192.168.1.49:32400      192.168.1.196:46092     ESTABLISHED 12992/Plex Media Se
udp        0      0 192.168.1.49:45899      78.46.223.24:53         ESTABLISHED 12992/Plex Media Se
udp        0      0 192.168.1.49:47160      162.242.211.137:53      ESTABLISHED 12992/Plex Media Se
```

So, I don't see anything like crazy except two of my LAN clients (Android TVs) are indeed holding a connection though nothing is playing.  Other WAN IPs appear to be complained about in Plex Forums finally being found out as Plex infrastructure IPs.

```
root@homeserver:/etc/plexupdate# bash plexupdate.sh -f
Retrieving list of available distributions
File already exists (plexmediaserver_1.12.0.4829-6de959918_amd64.deb), won't download.
ERROR: Server 192.168.1.49 is currently being used by one or more users, skipping installation. Please run again later
root@homeserver:/etc/plexupdate# 
```

**Comment by demonbane** [comment] 2018-03-10 04:15
Oh, it looks like it switched back to master. You'll need to do `git fetch && git checkout verbose-for-227` again.

**Comment by brimur** [comment] 2018-03-10 10:18
Hi guys, just came here because I noticed Plex was no longer updating. I am see the same message. I re ran the installer.sh and then said to run now with the settings but same error...

````
Configuration complete. Would you like to run plexupdate with these settings now? [Y/n] Y
Retrieving list of available distributions
File already exists (plexmediaserver_1.12.0.4829-6de959918_amd64.deb), won't download.
ERROR: Server 127.0.0.1 is currently being used by one or more users, skipping installation. Please run again later
````

**Comment by demonbane** [comment] 2018-03-10 10:27
@brimur can you please try the branch I made for this bug and paste the output here? From your plexupdate directory, run:

`git fetch && git checkout verbose-for-227`

And then run `plexupdate.sh -f`.

**Comment by brimur** [comment] 2018-03-10 10:51
@demonbane Sure...

````
Retrieving list of available distributions
File already exists (plexmediaserver_1.12.0.4829-6de959918_amd64.deb), won't download.
Entered running
Connecting to "127.0.0.1" on port "32400"
First wget returned 6, with data:


Second wget returned 6, data is now:


Entering https block
TOKEN is non-zero, continuing
First https wget returned 0, with data:
<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="0">
</MediaContainer>

Second https wget returned 0, data is now:
<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="0">
</MediaContainer><?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="0">
</MediaContainer>

GNU Awk 4.1.3, API: 1.1 (GNU MPFR 3.1.4, GNU MP 6.1.0)
Copyright (C) 1989, 1991-2015 Free Software Foundation.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see http://www.gnu.org/licenses/.

mediacount is now "1"

ERROR: Server 127.0.0.1 is currently being used by one or more users, skipping installation. Please run again later
````

**Comment by JoyDistelbrink** [comment] 2018-03-10 11:30
Hi guys ! Same error here : 

`Retrieving list of available distributions
File already exists (plexmediaserver_1.12.0.4829-6de959918_amd64.deb), won't download.
Entered running
Connecting to "91.121.210.40" on port "32400"
First wget returned 6, with data:


Second wget returned 6, data is now:
Entering https block
TOKEN is non-zero, continuing
First https wget returned 0, with data:
<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="0">
</MediaContainer>

Second https wget returned 0, data is now:
<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="0">
</MediaContainer><?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="0">
</MediaContainer>

awk: not an option: --version

mediacount is now "1"

ERROR: Server 91.121.210.40 is currently being used by one or more users, skipping installation. Please run again later
`

**Comment by derekcentrico** [comment] 2018-03-10 12:07
Okay I get the same as @brimur after resolving the git issue.

```
Retrieving list of available distributions
File already exists (plexmediaserver_1.12.0.4829-6de959918_amd64.deb), won't download.
Entered running
Connecting to "192.168.1.49" on port "32400"
First wget returned 6, with data:


Second wget returned 6, data is now:


Entering https block
TOKEN is non-zero, continuing
First https wget returned 0, with data:
<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="0">
</MediaContainer>

Second https wget returned 0, data is now:
<?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="0">
</MediaContainer><?xml version="1.0" encoding="UTF-8"?>
<MediaContainer size="0">
</MediaContainer>

GNU Awk 4.1.3, API: 1.1 (GNU MPFR 3.1.4, GNU MP 6.1.0)
Copyright (C) 1989, 1991-2015 Free Software Foundation.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see http://www.gnu.org/licenses/.

mediacount is now "1"

ERROR: Server 192.168.1.49 is currently being used by one or more users, skipping installation. Please run again later
root@homeserver:/etc/plexupdate# 
```

**Comment by salbahra** [comment] 2018-03-10 17:28
I am also investigating why my Plex server stopped updating and this is the exact reason for me to. I am also getting the same output as above (so I won't paste). I can confirm that stopping the server allows plex update to work. The issue is it's misreading the mediacount, somehow.

**Comment by demonbane** [comment] 2018-03-10 20:54
Quick update here, I'm now able to reproduce the issue. I suspect it's something to do with the version of awk everyone affected seems to have installed (4.1.3), but I'm still tracking it down.

**Comment by demonbane** [comment] 2018-03-10 21:16
I'm still trying to understand **why** this was the issue, but I at least found it. Fix should be out in a few minutes.

**Comment by derekcentrico** [comment] 2018-03-10 21:21
All good man.  We appreciate the help.  I'm glad to have a solution (never looked until recently) to auto install updates on Ubuntu.  Was a pain in the rear to install all the rolling betas.

**Closed** 2018-03-10 21:32 UTC
